// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjs6IkT2xyjJQqxv3kHzmyv9M0JRk3gik',
    appId: '1:1061055528733:web:115544990779245f1aabf4',
    messagingSenderId: '1061055528733',
    projectId: 'menu-food-bd6dd',
    authDomain: 'menu-food-bd6dd.firebaseapp.com',
    storageBucket: 'menu-food-bd6dd.firebasestorage.app',
    measurementId: 'G-EMB1WKY9SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdTNRv0dqXgD4XnL0ZRKZBgSp5kTShDGE',
    appId: '1:1061055528733:android:60e50c73ec6677701aabf4',
    messagingSenderId: '1061055528733',
    projectId: 'menu-food-bd6dd',
    storageBucket: 'menu-food-bd6dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFHLlx2mIPe8yIbMg3MDnscWNafNR6JJc',
    appId: '1:1061055528733:ios:3a363a693b5876031aabf4',
    messagingSenderId: '1061055528733',
    projectId: 'menu-food-bd6dd',
    storageBucket: 'menu-food-bd6dd.firebasestorage.app',
    iosBundleId: 'com.example.foodMenuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFHLlx2mIPe8yIbMg3MDnscWNafNR6JJc',
    appId: '1:1061055528733:ios:3a363a693b5876031aabf4',
    messagingSenderId: '1061055528733',
    projectId: 'menu-food-bd6dd',
    storageBucket: 'menu-food-bd6dd.firebasestorage.app',
    iosBundleId: 'com.example.foodMenuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjs6IkT2xyjJQqxv3kHzmyv9M0JRk3gik',
    appId: '1:1061055528733:web:310ef504455a1a321aabf4',
    messagingSenderId: '1061055528733',
    projectId: 'menu-food-bd6dd',
    authDomain: 'menu-food-bd6dd.firebaseapp.com',
    storageBucket: 'menu-food-bd6dd.firebasestorage.app',
    measurementId: 'G-F4GLL59LCW',
  );
}
